accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    # ex: /accounts/
    path('register', views.register, name='register'),
    # ex: /accounts/login
    path('login/', views.login, name='login'),
    # ex: /accounts/logout
    path('logout/', auth_views.LogoutView.as_view(template_name='computers/home.html',
                                                  next_page='/'),
         name='logout'),
]

computers/urls.py
from django.urls import path

from . import views

app_name = 'computers'
urlpatterns = [
    # ex: /
    path('', views.home, name='home'),
    # ex: /computers/id
    path('computers/<int:computer_id>/', views.detail, name='detail'),
]

ucr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('', include('computers.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from __future__ import annotations

computers/models.py
from django.db import models


class Computer(models.Model):
    name = models.CharField(max_length=200)
    brand = models.CharField(max_length=200)
    picture = models.URLField()
    rent = models.FloatField()
    stocks = models.IntegerField(default=0)
    os = models.CharField(max_length=200, blank=True)
    DISP_size = models.IntegerField(default=13, blank=True)
    RAM = models.IntegerField(default=4, blank=True)
    USB_port_num = models.IntegerField(default=4, blank=True)
    HDMI_port_num = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.name + " " + self.brand

    def was_out_of_stock(self):
        return self.stocks <= 0

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "password"]

    def save(self, commit: bool = True) -> User:
        user = super().save(commit=False)
        # encrypt password from plain text to hashed text
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect

from .forms import UserRegistrationForm


@require_http_methods(["GET", "POST"])
def register(request: HttpRequest) -> HttpResponse:

    if request.method == "GET":
        return render(request, "accounts/register.html")

    if (form := UserRegistrationForm(request.POST)).is_valid():
        user = form.save()
        auth_login(request, user)

        return redirect(reverse('computers:home'))

    # an invalid registration form was posted to here
    return render(request, "accounts/register.html")


@require_http_methods(["GET", "POST"])
def login(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        return render(request, 'accounts/login.html')

    if request.method == "POST":
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
        except KeyError:
            # Redisplay the computer homepage
            return render(request, 'computers/home.html', {
                'error_message': "Please fulfill the login form.",
            })
        else:
            # credentials error
            if user is None:
                # Redisplay the computer homepage
                return render(request, 'computers/home.html', {
                    'error_message': "Login failed",
                })

            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the back button.
            auth_login(request, user)
            return redirect(reverse('computers:home'))

    # Request method neither GET nor POST, return to homepage
    return render(request, 'computers/home.html', {'error_message': "Wrong request method"})

computers/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required

from .models import Computer


# Create your views here.
@require_http_methods(["GET"])
def home(request: HttpRequest) -> HttpResponse:
    computers = Computer.objects.all()
    return render(request, 'computers/home.html', {'computer_list': computers})


@login_required(login_url='/accounts/login')
@require_http_methods(["GET"])
def detail(request: HttpRequest, computer_id: int) -> HttpResponse:
    try:
        computer = get_object_or_404(Computer, pk=computer_id)
    except(KeyError, Computer.DoesNotExist):
        # Redisplay homepage
        return render(request, 'computers/home.html', {
            'error_message': "Please choose a exist computer and see its detail",
        })
    else:
        return render(request, 'computers/detail.html', {'computer': computer})

accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div>
        <h1 class="display-1">Login In</h1>

        <form action="{% url 'accounts:login' %}" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block content %}
    <div class="container mb-8">
        <h1 class="display-1">Sign Up Now</h1>

        <form action="{% url 'accounts:register' %}" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username">
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1">
          </div>
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
{% endblock content %}

computers/templates/computers/detail.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row row-cols-2">
            <div class="col">
                <img src = "{{computer.picture}}"
                     class="img-fluid img-detail" alt = "{{computer.name}}">
            </div>
            <div class="col">
                <p class="fs-1">{{computer.name}}</p>
                <p class="fw-bolder pt-2">
                    ${{computer.rent}} / hour
                </p>
                {% if computer.stocks > 0 %}
                    <p class="fw-light pt-1">More than {{computer.stocks}} available</p>
                {% else %}
                    <p class="fw-bold pt-1 text-danger">Rent Out</p>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container pt-5">
        <ul class="list-group">
            <li class="list-group-item"><p class="fw-bolder">OS:</p> {{computer.os}}</li>
            <li class="list-group-item"><p class="fw-bolder">Display Size:</p> {{computer.DISP_size}} inch</li>
            <li class="list-group-item"><p class="fw-bolder">RAM:</p> {{computer.RAM}} GB</li>
            <li class="list-group-item"><p class="fw-bolder">USB Port Number:</p> {{computer.USB_port_num}}</li>
            <li class="list-group-item"><p class="fw-bolder">HDMI Port:</p> {{computer.HDMI_port}}</li>
        </ul>

    </div>
{% endblock content %}

computers/templates/computers/header.html
<!-- Bootstrap .navbar-brand for your company, product, or project name. -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- As a Heading -->
        <span class="navbar-brand mb-0 h1">UCR</span>
        <!-- As a link -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <!-- Add the .active class on .nav-link to indicate the current page.
                     Please note that you should also add the aria-current attribute on the active .nav-link.-->
                <a class="nav-link" aria-current="page" href="{% url 'computers:home' %}">Home</a>
            </div>
        </div>
    </div>

    <!-- Authenticated Dropdown -->
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item dropstart">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    {% endif %}
</nav>

computers/templates/computers/home.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row row-cols-2">
            <div class="col-9" id="home-welcome-box">
                <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://cdn.jsdelivr.net/gh/cat-imado/imado-s-live@main/UTAS/urc-homepage-welcome-pic-3.png" class="img-fluid" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://cdn.jsdelivr.net/gh/cat-imado/imado-s-live@main/UTAS/urc-homepage-welcome-pic-2.png" class="img-fluid" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://cdn.jsdelivr.net/gh/cat-imado/imado-s-live@main/UTAS/urc-homepage-welcome-pic-5.png" class="img-fluid" alt="...">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>

            <div class="col-3">
                {% if not user.is_authenticated %}
                <div>
                    <form action="{% url 'accounts:login' %}" method="post">
                      {% csrf_token %}
                      <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username">
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                      </div>
                      <button type="submit" class="btn btn-primary">Login</button>
                      <a href="{% url 'accounts:register' %}"><button type="button" class="btn btn-secondary">Sign Up</button></a>
                    </form>
                </div>

                {% else %}
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">Welcome Back</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ user.username }}</h6>
                        <div class="spinner-grow text-primary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="spinner-grow text-secondary" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="spinner-grow text-success" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="spinner-grow text-danger" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="spinner-grow text-warning" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="spinner-grow text-info" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <div class="spinner-grow text-light" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>

                        <a href="{% url 'accounts:logout' %}" class="btn btn-primary">Logout</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div>
        {% include "computers/show_list.html" %}
    </div>
{% endblock content %}

computers/templates/computers/show_list.html
<div class="mt-4 container-md" id="search-module">
    <div class="row row-cols-3 text-center">
        {% if computer_list %}
            {% for computer in computer_list %}
                <div class="col gy-3">
                    <div class="card h-100">
                        <img src = "{{ computer.picture }}"
                             class="card-img-top" alt = "{{ computer.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ computer.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ computer.brand }}</h6>
                            <p class="card-text">{{ computer.rent }} / hour</p>
                            <a href="{% url 'computers:detail' computer.id %}" class="btn btn-dark stretched-link">
                                View Details
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No computers are available.</p>
        {% endif %}
    </div>
</div>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>UCR</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <!-- header-->
    <header class="pb-3">
        {% include 'header.html' %}
    </header>

    {% block content %}{% endblock %}

    <!--footer-->
    <footer class="container">
        {% include 'footer.html' %}
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
<div class="container mt-5">
    <p>&copy; UCR powered by Django &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</div>

templates/header.html
<!-- Bootstrap .navbar-brand for your company, product, or project name. -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <!-- As a Heading -->
        <span class="navbar-brand mb-0 h1">UCR</span>
        <!-- As a link -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <!-- Add the .active class on .nav-link to indicate the current page.
                     Please note that you should also add the aria-current attribute on the active .nav-link.-->
                <a class="nav-link" aria-current="page" href="{% url 'computers:home' %}">Home</a>
            </div>
        </div>
    </div>

    <!-- Authenticated Dropdown -->
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item dropstart">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>

                        {% if user.is_superuser %}
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Dashboard</a></li>
                        </ul>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    {% endif %}
</nav>